# -*- coding: utf-8 -*-

"""
/***************************************************************************
 Layer2KMZ
                                 A QGIS plugin

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-05-10
        copyright            : (C) 2020 by Pedro Tarroso
        email                : https://github.com/ptarroso
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Pedro Tarroso'
__date__ = '2020-05-10'
__copyright__ = '(C) 2020 by exp1'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.core import QgsProcessingAlgorithm, QgsApplication
from .layer2kmz_provider import layer2kmzProvider
from .layer2kmz_GUI import layer2kmzGUI

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class layer2kmz(object):

    def __init__(self, iface):
        self.provider = None
        self.gui = layer2kmzGUI(iface)

    def initProcessing(self):
        self.provider = layer2kmzProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()
        self.gui.initGui()

    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
        self.gui.unload()
